[성주호] Mission 2: 모델링
wecode-bootcamp-korea/27-westagram-backend-2-team pull request #11
Opened 2021-11-18 12:42 UTC by Joshua-sung

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-18 15:49 UTC, kyeongraekim requested changes
아래 내용 참고하여 수정해주세요!~

2021-11-18 15:49 UTC, kyeongraekim commented on students/jooho/users/models.py
> +    email      = models.EmailField(max_length=20,unique=True)
email field 의 제한 length 가 너무 적습니다~ 100자~200자 선으로 으로 늘려주세요.

2021-11-18 15:49 UTC, kyeongraekim commented on students/jooho/users/models.py
> +    password   = models.CharField(max_length=20)
비밀번호는 추후에 암호화하여 저장될 기획에 대비하여 max_length 를 200자는 주셔야 합니다.

2021-11-18 15:49 UTC, kyeongraekim commented on students/jooho/users/models.py
> +    phonenumber = models.CharField(max_length=20)
snake case 로 변수명을 적절히 띄어주세요. 국제 전화 번호의 경우에 Length가 20자보다 길어질 수도 있습니다. 이 부분도 조금더 늘려주세요~

2021-11-18 15:49 UTC, kyeongraekim commented on students/jooho/users/models.py
> +    birthday   = models.CharField(max_length=20)
birthday는 정확한 날짜가 기입되는 곳이니 Charfield 말고 해당되는 field를 넣어주셔야겠죠?

2021-11-18 15:49 UTC, kyeongraekim commented on students/jooho/users/models.py
> +    gender     = models.CharField(max_length=20)
gender 아래 해당 내용에 대한 이력관리를 위해 created_at과 updated_at을 추가해주세요!

2021-11-18 15:53 UTC, Joshua-sung commented on students/jooho/users/models.py
> +    gender     = models.CharField(max_length=20)
확인했습니다. 늦은 밤인데도 봐주셔서 감사합니다 좋은 밤 되셔요

2021-11-19 06:07 UTC, kyeongraekim requested changes
아래 내용 마지막으로 추가 수정해서 반영해주세요!~

2021-11-19 06:07 UTC, kyeongraekim commented on students/jooho/users/models.py
> +    birthday    = models.DateField(blank=True,null=True)#생일 정보를 입력하고 싶지않은 이용자는 빈칸으로 사용가능
개인 메모용 한글 주석이 불필요하게 남아있네요!~ 해당내용 삭제해주세요!

2021-11-19 06:07 UTC, kyeongraekim commented on students/jooho/users/models.py
> +    gender      = models.CharField(max_length=20,blank=True,null=True)
Charfield 는 보통. blank, null 을 두개 다 True로 설정하지 않습니다. 해당 내용 리서치 한 번 해주세요~

2021-11-19 06:07 UTC, kyeongraekim commented on students/jooho/users/models.py
> +
불필요한 공백이 여러칸 보이네요~

2021-11-19 07:39 UTC, merged