[고민혁] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/27-westagram-backend-2-team pull request #14
Opened 2021-11-19 06:56 UTC by MinhyukK0

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 구현 및 url 타겟 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-users.views.py Userview 클래스 작성
- 1. 기본 회원가입
- 2. 회원가입시 이메일 및 비밀번호 공백 체크
- 3. 회원가입시 이메일 중복체크
- 4. 회원가입시 이메일 및 비밀번호 정규표현식 검사

-westagram.urls.py 수정
-users.urls.py 수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-19 09:12 UTC, kyeongraekim requested changes
민혁님~ 아래 내용 참고해서 확인해주세요!

2021-11-19 09:12 UTC, kyeongraekim commented on students/minhyukko/users/views.py
>  from django.shortcuts import render
사용하지 않은 불필요한 import 문은 삭제해주세요!~

2021-11-19 09:12 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +        regexr_email    = re.compile('[a-zA-Z0-9]+\.?\w*@\w+[.]?\w*[.]+\w{2,3}')
장고-파이썬 코드 상 compile 보다는 match 가 권장되는 편입니다. 그 사유에 대해 고민해보시고 수정 반영해주세요!~

2021-11-19 09:12 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +            # email과 password가 비어있는 경우
제 3자의 개발자가 코드로 충분히 독해 가능한 부분으로 판단되며 불필요한 한글 설명 주석은 삭제해주세요!~

2021-11-19 09:12 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +                return JsonResponse({'message':'Email or Password is Blank'}, status = 400)
비밀번호와 이메일 둘 중 어느 부분에서 에러가 나왔는지 명시하기 위해서 조건절을 두개로 나누어 보시는걸 추천드려요!~

2021-11-19 09:12 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +                raise JsonResponse({'message' : 'Email Reduplication'}, status=400)
- 불필요한 if - elif 중첩으로 보입니다~ 과도한 중첩을 줄여 보는 것이 어떨까요?
- 웹 개발에서의 변수명은 코드 문제 풀이시 사용될 법한 'i'가 아닌 정확한 영어 명칭을 full로 사용해주셔야 합니다. 적절한 변수명으로 바꾸어 주세요!~
- 또한 Email Reduplication 이라는 다소 어색한 영어 표현보다  Duplicated_Email 이라는 표현이 더 나아보이네요!

2021-11-19 09:12 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +                raise ValueError
validationerror 를 따로 import 하셔서 커스터마이징된 메세지와 함께 리턴하는 법이 있습니다. 
raise ValidationError('INVALID_PASSWORD')
해당 내용을 한번 참고해주세요!~

2021-11-19 09:12 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +                information = data['information']
실제 인스타그램 기획상 주소와 추가 정보는 나중에 회원가입 이후에 update 되는 형식으로 되어있죠?
모델링 때 이 둘에 대한 null=True 값을 속성값으로 주셨다면 키에러만을 일으키지 않는 Null 값도 실제로 다루어볼 수 있는 더 좋은 기획이 되었을 것 같습니다!~ 참고만 해주세요~

2021-11-19 13:19 UTC, MinhyukK0 commented on students/minhyukko/users/views.py
> +                information = data['information']
users.models.py에 반영해서 information 필드값에 null =True 속성값 추가했습니다!

2021-11-19 13:19 UTC, MinhyukK0 commented on students/minhyukko/users/views.py
> +                raise ValueError
커스터마이징 기능 알려주셔서 감사합니다 ^^ users.views.py 에 반영했습니다 !

2021-11-19 13:21 UTC, MinhyukK0 commented on students/minhyukko/users/views.py
> +                raise JsonResponse({'message' : 'Email Reduplication'}, status=400)
불필요한 중복된 이메일 값 처리는 except IntegrityError로 처리했습니다!

2021-11-19 13:21 UTC, MinhyukK0 commented on students/minhyukko/users/views.py
> +                return JsonResponse({'message':'Email or Password is Blank'}, status = 400)
조건절 두개로 나눠서 작성완료했습니다! :)

2021-11-19 13:21 UTC, MinhyukK0 commented on students/minhyukko/users/views.py
>  from django.shortcuts import render
삭제 완료했습니다! ^^

2021-11-19 13:23 UTC, MinhyukK0 commented on students/minhyukko/users/views.py
> +        regexr_email    = re.compile('[a-zA-Z0-9]+\.?\w*@\w+[.]?\w*[.]+\w{2,3}')
현재 view.py 에서 정규 표현식 검사를 한번만 필요로 하기때문에 불필요한 컴파일(컴파일 캐시 생성)을 줄이고자 re.match로 변경하였습니다.

2021-11-19 13:24 UTC, MinhyukK0 commented
요청사항 수정 완료했습니다! :D

2021-11-20 08:07 UTC, MinhyukK0 commented on students/minhyukko/users/views.py
> +            # email과 password가 비어있는 경우
삭제했습니다!

2021-11-21 15:05 UTC, kyeongraekim requested changes
안녕하세요 민혁님~ 아래 내용 참고하셔서 수정해주세요!~

2021-11-21 15:05 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +from django.db.utils import IntegrityError
해당 내용 위코드 컨벤션에 맞게 깔끔한 재정렬 부탁드립니다!~

2021-11-21 15:05 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +                raise ValidationError('Password_is_Blank')
파이선 딕셔너리 문법 중 abc['efg'] 가 아닌 .get() 메소드를 써서 진행해보신다면 if 조건문의 논리 공백이 조금 더 채워질 것 같습니다. 

해당 메소드는 찾는 키가 없을 때 Null 값을 디폴트로 반환한다는 특징을 지니고 있습니다~

2021-11-21 15:05 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +        except ValidationError as e:
실제 에러 메세지를 위와 같이 모두 반환하게 된다면 클라이언트/프론트 단에서 해당 에러 메세지를 모두다 읽을 수 있게 됩니다. 보안상  취약성이 드러나기 때문에 위와 같이 디버깅 단계에서는 사용될 수 있겠으나 클라이언트측에게 리턴 메세지로는 반환해주시면 안된다는 점을 당부드립니다!~

2021-11-22 00:42 UTC, MinhyukK0 commented on students/minhyukko/users/views.py
> +from django.db.utils import IntegrityError
수정 완료했습니다! :)

2021-11-22 00:43 UTC, MinhyukK0 commented on students/minhyukko/users/views.py
> +                raise ValidationError('Password_is_Blank')
get메서드로 조건문 작성완료했습니다! ^^

2021-11-22 00:43 UTC, MinhyukK0 commented on students/minhyukko/users/views.py
> +        except ValidationError as e:
알려주셔서 감사합니다! 
디버깅 단계에서만 알 수 있도록 다시 처리하였습니다!

2021-11-22 00:44 UTC, MinhyukK0 commented
리뷰요청 수정 완료하였습니다.

2021-11-22 01:39 UTC, kyeongraekim requested changes
민혁님 굿모닝입니다!~ 아래 내용 확인해서 수정반영해주세요~

2021-11-22 01:39 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +                information = data['information']
네 잘 변경해주셨네요! 그렇다면 디폴트를 null 값으로 받을 수 있게 information 매핑을 abc['def'] 형식이 아닌 get.() 메소드를 사용해보세요!~

2021-11-22 02:28 UTC, MinhyukK0 commented
수정 완료했습니다!
세세한 리뷰 감사합니다! 
파이썬 기본의 dict메서드에 대한 공부가 되었습니다^^ :D

2021-11-22 02:35 UTC, kyeongraekim requested changes
네 민혁님! 불필요한 파일만 삭제해주시고 다시 한 번 푸시해주세요!~

2021-11-22 02:35 UTC, kyeongraekim commented on .vscode/settings.json
> +}
불필요한 파일이 생성되어서 올라왔네요!~ 깃허브상 올라오지 않도록 git cache 를 삭제했다가 다시 애드 커밋하신 후 올려주세요!~

2021-11-22 02:35 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +            if re.match(regexr_email, data['email']) is None or re.match(regexr_password,data['password']) is None:
-  이 곳에서 Validation Error를 잡아달라고 했던 점은 해당 리뷰 내용은 추후 validations.py 로의 모듈화를 위한 사전 연습(?)의 일환임을 미리 말씀드립니다 ㅎㅎ! validation을 잡아주는 파일을 따로 만들어서 import 해주고, view에서는 validation Error로 잡는 내용에 대한 원리를 하나씩 깨우쳐가기위해 단계별로 리뷰를 달아드렸습니다!~ 다음 로그인 세션 때 한 번 모듈화에 도전해보세요!~

2021-11-22 03:33 UTC, MinhyukK0 commented
수정 완료했습니다!

2021-11-22 06:32 UTC, kyeongraekim requested changes
한 부분 더 마저 수정 부탁드려요 민혁님!~

2021-11-22 06:32 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +        except ValidationError:
이곳은 key_error 를 잡아주는 곳임으로 except KeyError 가 올바른 작성이 되겠네요!~

2021-11-22 06:58 UTC, MinhyukK0 commented
오타 확인 하지 않아서 여러번 푸시했습니다. ㅠ 죄송합니다!

2021-11-22 07:11 UTC, kyeongraekim approved these changes

2021-11-22 07:12 UTC, kyeongraekim commented
LGTM!~

2021-11-22 07:12 UTC, merged