Feature/dowon signup
wecode-bootcamp-korea/27-westagram-backend-2-team pull request #15
Opened 2021-11-19 12:21 UTC by rosewoodowon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입 데이터 저장
- 이메일 중복시 400 반환
- 비밀번호 최소 8 자, 대문자 하나 이상, 소문자 하나, 숫자 하나 및 특수 문자 하나 이상 정규식 적용
- 실패시 에러 반환
- 성공시 201 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
이전에 models.py 작성 시 email 과 phone_number 에 unique=True 속성을 주었었는데, POST 할 때 django.db.utils.IntegrityError: (1062, "Duplicate entry '' for key 'users.phone_number'") 이 에러가 떠서 phone_number unique 속성을 drop 한 뒤 데이터를 넣었습니다. 데이터를 POST로 입력할 때 다른 데이터랑 중복되지 않는 다른 번호를 적었는데도 에러가 나는 이유가 궁금합니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-21 14:53 UTC, kyeongraekim requested changes
도원님 안녕하세요~ 아래 수정사항 확인해주시고 반영해주세요!~

2021-11-21 14:53 UTC, kyeongraekim commented on students/dowon/.vscode/settings.json
> +    "python.pythonPath": "/opt/homebrew/Caskroom/miniconda/base/envs/we27/bin/python"
깃허브 업로드에/ 코드 작업에 불필요한 내용은 삭제해주세요!~

2021-11-21 14:53 UTC, kyeongraekim commented on students/dowon/users/views.py
> +import json, bcrypt, jwt, re
bcrypt, jwt 까지 미리 앞서 가신 점 너무 칭찬드리고 싶네요~ 다만 미션별로 해당 내용을 제출해주셨으면 하는 마음에 해당 내용은 삭제 후 mission 4 & 5진행 시 재푸시해주세요~

2021-11-21 14:53 UTC, kyeongraekim commented on students/dowon/users/views.py
> +from my_settings import SECRET_KEY, DATABASES
import 문 위코드 컨벤션에 맞게 깔끔하게 재정렬 부탁드립니다!~

2021-11-21 14:53 UTC, kyeongraekim commented on students/dowon/users/views.py
> +            information  = data['information']
인스타 그램은 추가 정보 기입이 회원가입이 완료된 이후에 추가 기입 사항으로 설정되어있습니다. 만일 information이 무조건 키에러를 내야하는 사항이 아닌 null 값도 허용이 되어있었다면 보다 실제 서비스에 부합하는 코드가 되었을 것 같네요!~

2021-11-21 14:53 UTC, kyeongraekim commented on students/dowon/users/views.py
> +            #password_crypt = bcrypt.hashpw(password, bcrypt.gensalt()).decode('utf-8')
불필요한 코드 내용은 삭제해주세요!~

2021-11-21 14:53 UTC, kyeongraekim commented on students/dowon/users/views.py
> +            return JsonResponse({'message' : 'KEY_ERROR'}, status=400)
위 내용을 통해 발생할 수 있는 에러의 경우의 수가 키에러외에도 여러개 있을 것 같아 보여요!~
개발자의 시각에서 보다 다양한 에러 사항에 대한 핸들링을  고민해보세요!~

2021-11-22 01:36 UTC, kyeongraekim requested changes
도원님~ 작성해드린 수정 사항이 아직 미반영되어있는 것 같네요! 혹시 해결하시면서 궁금하셨던 내용있으시면 코멘트로 남겨주세요!~

2021-11-22 02:31 UTC, Djangowon commented
import문 정렬하고 불필요한 bcrypt, jwt 코드 삭제했습니다. information 은 null 값 허용 속성만 주고 post 도 해보았는데 키에러가 나지 않도록 뷰에서 키 삭제하는 것이 좋을 것 같아 삭제했습니다! 혹시 git diff로 보는 것 외에 깃헙 상에서 어느 부분이 바뀌었는지 보여지는 것 말고 수정이 완료된 코드들만 볼 수 있는 방법이 있나요?

2021-11-22 06:42 UTC, kyeongraekim commented
LGTM!~ 고생하셨습니다! Mission 4에서는 Validation 내용을 따로 파이썬 파일로 만드는 (모듈화) 작업을 주문할 예정입니다. 관련 내용 미리 학습해주세요~

2021-11-22 06:42 UTC, kyeongraekim approved these changes

2021-11-22 06:42 UTC, merged