[장도원] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/27-westagram-backend-2-team pull request #18
Opened 2021-11-22 07:05 UTC by Djangowon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일로 로그인할 수 있음
- 실패시 400 에러 반환
- 성공시 200 OK 반환
- 이메일 또는 비밀번호 틀렸을 시 401 에러 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-22 07:29 UTC, kyeongraekim commented
도원님! 3단계 때 해주셨던 validation과 관련해 이번 기회에 모듈화에 도전해보세요~ validation.py/validator.py 형식의 새로운 파이썬 코드를 짜주시면 됩니다.

2021-11-22 12:52 UTC, jumyeong33 commented on students/dowon/users/views.py
> +from django.db.models import Q
Q는 뭘까요?!

2021-11-22 12:52 UTC, jumyeong33 commented on students/dowon/users/views.py
> +               return JsonResponse({'massage': 'INVALID_ERROR'}, status=401)
같은 에러메세지를 보내는거라면 and를 써서 합치는 건 어떨까요?!

2021-11-22 12:53 UTC, MinhyukK0 commented on students/dowon/users/views.py
> +            if not User.objects.filter(password=data['password']):
filter 문으로 종료하게되면 QuerySet을 반환하게 됩니다. :D

2021-11-22 12:53 UTC, MinhyukK0 commented on students/dowon/users/views.py
> +
위에서 말씀드렸다시피 filter문으로 끝나게되면 QuerySet을 반환받게됩니다.ㅠㅠ

2021-11-22 12:53 UTC, MinhyukK0 commented on students/dowon/users/views.py
> +
++) A의 이메일과 B의 비밀번호를 입력받아도 로그인에 성공하게됩니다 ㅠㅠ

2021-11-22 15:34 UTC, kyeongraekim requested changes
도원님~ 아래 내용 확인후 수정 반영해주세요!~

2021-11-22 15:34 UTC, kyeongraekim commented on students/dowon/users/views.py
> +
Q객체를 사용하지 않고 filter() 메소드 선에서 위에 해당되는 로직을 적용하셔야 맞아 보입니다.
Q객체를 언제 왜 사용하는지에 대한 고민을 다시 한 번만 해주세요!~

2021-11-22 15:34 UTC, kyeongraekim commented on students/dowon/users/views.py
> +               return JsonResponse({'massage': 'INVALID_ERROR'}, status=401)
```python
user = User.objects.get(email = email)

if not User.objects.filter(email=email).exists() :
    return JsonResponse({"message": "INVALID_USER"}, status = 401)
```

email로 조회했을 때 데이터베이스에 매칭되는 데이터가 없는 경우 python에서 error를 raise 합니다. 그렇기 때문에 `if not User.objects.filter(email=email).exists() :` 코드가 실행될 일이 없겠죠?

그러므로 위 if문 코드는 불필요한 코드입니다. `user = User.objects.get(email = email)` 에서 에러가 발생했을 경우에 except문에서 에러를 잡아줄 수 있도록 수정해주세요.

2021-11-23 06:21 UTC, kyeongraekim requested changes
도원님 추가 수정 사항 반영해주세요~

2021-11-23 06:21 UTC, kyeongraekim commented on students/dowon/users/views.py
> +
마지막 부분에 불필요한 공백이 보이네요!~

2021-11-23 06:21 UTC, kyeongraekim commented on students/dowon/users/views.py
> +
object를 두번 부르지 않는 선에서 filter를 걸 수 있습니다!~ 해당 내용으로 수정변경해주세요~

2021-11-23 06:33 UTC, kyeongraekim requested changes
마지막 수정사항 반영 부탁드립니다~

2021-11-23 06:33 UTC, kyeongraekim commented on students/dowon/users/validation.py
> +        raise ValidationError('INVALID_PASSWORD')
도원님 마지막 추가 수정사항으로 validation.py내 이메일과 패스워드 유효성 검증 함수를 나누어 주세요!~ 모듈은 한 번에 하나의 기등을 하게 만들면 좋습니다!~ 미래 확정성을 고려한 코드를 지향해주세요~

아래와 같은 구조로 만드시는걸 추천드려요~

```python
import re

from django.core.exceptions import ValidationError

REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

def validate_email(email) :    
    ...
def validate_password(password) :
    ...)
```

2021-11-23 06:39 UTC, Djangowon commented
수정 완료 했습니다 ㅎㅎ

2021-11-23 06:47 UTC, Djangowon commented
> 

수정완료 했습니다!

2021-11-23 06:48 UTC, kyeongraekim requested changes
최최최종 수정 피드백 드립니다~

2021-11-23 06:48 UTC, kyeongraekim commented on students/dowon/users/validation.py
> +        raise ValidationError('INVALID_PASSWORD')
진짜 4단계에서의 마지막 수정사항이 될 것 같네요~ if not 과 if is None 두 내용에 대한 비교를 한 번 해주시고 어느 것이 더 나을지 고민해 보세요!~

2021-11-23 07:32 UTC, kyeongraekim approved these changes
LGTM!~

2021-11-23 07:32 UTC, merged