Feature/minhyukko signin
wecode-bootcamp-korea/27-westagram-backend-2-team pull request #20
Opened 2021-11-22 08:58 UTC by MinhyukK0

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- users.views SigninView 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 더 나은 방향을 제시해주신 경래님께 감사드립니다! 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-22 12:43 UTC, jumyeong33 commented on students/minhyukko/users/views.py
> +from django.db.models       import Q
Q 는 뭐하는 녀석인가요!?

2021-11-22 12:43 UTC, jumyeong33 commented on students/minhyukko/users/views.py
>          regexr_email    = '[a-zA-Z0-9]+\.?\w*@\w+[.]?\w*[.]+\w{2,3}'
세세한 에러 메세지 멋집니다. 모듈로 안빼시나요?

2021-11-22 12:50 UTC, haileyjpark commented on students/minhyukko/users/views.py
> +from django.db.models       import Q
Q 는 뭐하는 녀석인가요!?

2021-11-22 12:52 UTC, haileyjpark commented on students/minhyukko/users/views.py
> +from django.db.models       import Q
LGTM~

2021-11-22 15:10 UTC, kyeongraekim requested changes
다음 내용확인 후 수정해주세요!~

2021-11-22 15:10 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +            if User.objects.filter(Q(email = data['email']) & Q(password=data['password'])).exists():
해당 부분이 잘 작동하나요? 로그인 의도에 맞게 잘 작동하는지 확인 부탁드려요!~
Q객체에 대한 내용에 대한 이해는 어느정도 되어 있으신 것 같아 보이나,  
회원가입 로직에 맞게 이메일의 유무를 먼저 잡고 그 이메일에 해당되는 패스워드인지 에 대한 내용이 반영되어있지 않아 보이네요!~

2021-11-22 15:10 UTC, kyeongraekim commented on students/minhyukko/users/views.py
>          regexr_email    = '[a-zA-Z0-9]+\.?\w*@\w+[.]?\w*[.]+\w{2,3}'
validation 모듈을 4단계에서 완료해서 5-6단계 미션에서 사용할 수 있게 변경해보세요!~

2021-11-23 02:27 UTC, MinhyukK0 commented
모듈 작성 및 리뷰 요청사항 반영해서 수정했습니다!

2021-11-23 06:43 UTC, kyeongraekim requested changes
다음 내용 확인 후 수정해주세요!~

2021-11-23 06:43 UTC, kyeongraekim commented on students/minhyukko/users/validator.py
> +        raise KeyError('EMAIL_IS_BLANK')
데이터에서 blank와 null은 의미가 다르니 보다 명확한 에러메세지로 커스터마이징해주세요!~

2021-11-23 06:43 UTC, kyeongraekim commented on students/minhyukko/users/validator.py
> +        raise ValidationError('INVALID_KEY')
이메일과 비밀번호 정규표현식에 해당되는 함수를 각각 작성해주세요!~ 한 번에 처리 하는 것 보다 더 코드 확장성과 기능과 의미에 충실한 모듈 함수로 사용될 수 있습니다~

2021-11-23 06:43 UTC, kyeongraekim commented on students/minhyukko/users/validator.py
> +def is_regexr(email, password):
함수명 네이밍이 다소 어색하네요. email_validate 등으로 수정해주시면 좋을 것 같습니다~

2021-11-23 06:43 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +            user_pwd = User.objects.get(email=data['email']).password
- 변수명 컨벤션 좀더 신경써주세요~
- pwd 보다는 password와 같은 영어 원어를 전체 풀어써 주세요!~
- password를 기준으로 잡는 것보다 user를 기준으로 변수명을 잡아서 user.password 형식으로 코드에 녹여주실 수 있게 반영해주세요!~ 그러면 가독성이 올라갈 것 같네요
- 위에 대한 가독성 향상을 해보셨다면 email과 password 를 동시에 Filter로 조건을 걸면 더 좋아 보일 것 같네요!~

2021-11-23 07:07 UTC, MinhyukK0 commented
리뷰내용 모두 반영 완료했습니다!

2021-11-23 07:24 UTC, kyeongraekim requested changes
다음내용 확인하여 수정해주세요!~

2021-11-23 07:24 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +            if not User.objects.filter(email = data['email']).exists():
if not 이 아니고 if 로 진행해주셔야 duplicated_email이 나올 것 같네요!

2021-11-23 07:29 UTC, MinhyukK0 commented
죄송합니다! ㅠㅠ 
로직 오류 수정 완료했습니다!

2021-11-23 07:45 UTC, kyeongraekim approved these changes

2021-11-23 07:46 UTC, merged

2021-11-23 07:46 UTC, kyeongraekim commented
LGTM!~