[유민혁] Mission 4 : 로그인 기능 구현
wecode-bootcamp-korea/27-westagram-backend-2-team pull request #21
Opened 2021-11-22 11:27 UTC by MinHyeouk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
View.py 내에 signin 클래스 작성
		 
## 수정 사항들 자세한 내용
작성한 email != DB내의 email -> 실패!
작성한 비밀번호 != DB내의 비밀번호 -> 실패!
작성한 email = db email and 작성한 비밀번호 = db 비밀번호 -> 성공!

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [v] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [v] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [v] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [v] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-22 12:52 UTC, MinhyukK0 commented on students/minhyeouk/users/views.py
> +                return JsonResponse({'MESSAGE' : 'SUCCESS'}, status=200)
A의 아이디와 B의 비밀번호가 입력되면 로그인성공 메세지를 받게 됩니다.
로직 수정 부탁드립니다 ! ^^
다른 민혁 올림-

2021-11-22 12:52 UTC, jumyeong33 commented on students/minhyeouk/users/views.py
> +
여기에 공백을 준 이유는 뭔가여?

2021-11-22 12:52 UTC, jumyeong33 commented on students/minhyeouk/users/views.py
> +            if not User.objects.filter(email=data['email']).exists():
exists() 함수는 왜 사용하신 건가요?

2021-11-22 15:12 UTC, kyeongraekim requested changes
다른 분들 질문에 대한 답변도 친절히 달아주세요!~ 그리고 다음 내용 수정 반영 부탁드려요!~ 
수정 시 정규표현식 부분 이메일, 비밀번호에 대한 validation 내용을 모듈화하셔서 올려주세요!~

2021-11-22 15:12 UTC, kyeongraekim commented on students/minhyeouk/users/views.py
> +                return JsonResponse({'MESSAGE' : 'SUCCESS'}, status=200)
아 이곳에 민혁님이 잘 짚어주셨군요! 이메일을 필터로 객체를 먼저잡고 해당 이메일에 맞는 패스워드인지 확인하는 로직을 추가하셔야 할 것 같네요!

2021-11-23 01:52 UTC, MinHyeouk commented on students/minhyeouk/users/views.py
> +                return JsonResponse({'MESSAGE' : 'SUCCESS'}, status=200)
해결했습니다 !! 감사합니다 🥰

2021-11-23 01:56 UTC, MinHyeouk commented on students/minhyeouk/users/views.py
> +
안에 있는 return 값과 밖의 return 값이 달라서 공백을 줬습니다 !! 혹시 다른 의견 있으시면 언제든 말씀해주세요 주명님 !!

2021-11-23 02:02 UTC, MinHyeouk commented on students/minhyeouk/users/views.py
> +            if not User.objects.filter(email=data['email']).exists():
exists는 filter와 함께 사용해서 조건에 맞는 데이터가 있으면 True, 없으면 False를 주는 역할을 합니다 !! 여기선 db상에 해당 데이터가 있는지 확인하려면 필요하다고 생각했습니다 !!

2021-11-23 08:33 UTC, MinHyeouk commented
validation 완료 했습니다 !!

2021-11-23 15:55 UTC, kyeongraekim requested changes
민혁님! 주석들만 지워주시고 재푸시해주세요!~

2021-11-23 15:55 UTC, kyeongraekim commented on students/minhyeouk/users/views.py
> +            #     return JsonResponse({'MESSAGE' : 'INVALID_PASSWORD'}, status=400)
해당 주석처리된  내용들은 validation을 모듈화 해주셨다면 삭제해주셔도 무방해보이네요!~

2021-11-24 01:06 UTC, MinHyeouk commented on students/minhyeouk/users/views.py
> +            #     return JsonResponse({'MESSAGE' : 'INVALID_PASSWORD'}, status=400)
앗 바로 수정했습니다 경래님 !~ 감사합니다 !!

2021-11-24 01:11 UTC, kyeongraekim approved these changes
LGTM!~

2021-11-24 01:11 UTC, merged