[이주명] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/27-westagram-backend-2-team pull request #22
Opened 2021-11-22 12:28 UTC by jumyeong33

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 이름 또는 비밀번호 오류시 401 INVALID_USER 반환
- 이름 또는 비밀번호 키 부재시 400 KEY_ERROR 반환
- 성공시 200 SUCCESS 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-22 12:53 UTC, MinhyukK0 commented on students/jumyoeng/users/views.py
> +                return JsonResponse({'MESSAGE': 'INVALID_USER'}, status=401)
else를 안쓰셔도 되지 않을까요...?
제 기준에서 너무 완벽해서 억까해봅니다...ㅋㅋ

2021-11-22 15:22 UTC, kyeongraekim requested changes
아래 내용 확인해서 수정해주세요!~

2021-11-22 15:22 UTC, kyeongraekim commented on students/jumyoeng/users/views.py
> +            if User.objects.filter(name=data['name'], password = data['password']) :
- 로그인시 입력하는 정보의 판별 요소가 name 이 아닌 email 이 되어야 하지 않을까요?

- 그리고 filter로만 if 문에 남기는 것과 .exists()를 뒤에 덧붙이는 것에 대한 차이를 검토해주세요!~

2021-11-22 15:22 UTC, kyeongraekim commented on students/jumyoeng/users/views.py
> +                return JsonResponse({'MESSAGE': 'INVALID_USER'}, status=401)
- 민혁님 의견처럼 else문은 불필요해보입니다!~ 그 사유에 대해 한 번 생각해보세요!

2021-11-23 02:30 UTC, MinHyeouk commented
LGTM !! 많이 배우고 갑니다 주명님 !!

2021-11-23 06:09 UTC, kyeongraekim requested changes
안녕하세요 주명님 validation 관련 내용 수정 피드백 드립니다!~

2021-11-23 06:09 UTC, kyeongraekim commented on students/jumyoeng/users/my_lib/validation.py
>      if len(password) < 8 :
주명님 다음의 내용 한 번 확인해서 반영해주세요!~
Validation.py 에 대한 접근을 과제로 나가기 전에 잘 접근해주셨으나 불필요한 if-elif-else 구문이 증식한 형태로 보여집니다. 
validate 를 통해서 확인하셔야 할 부분은 들어온 input 값이 내 view 파일 내에 비즈니스 로직을 훑기전에 올바른 형태인가를 확인해주는 것입니다~ 참고해주세요!

```python
import re

from django.core.exceptions import ValidationError

REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

def validate_email(value) :    
    if not re.match(REGEX_EMAIL, value):
        raise ValidationError('INVALID_EMAIL_ADDRESS')

def validate_password(value) :
    if not re.match(REGEX_EMAIL, value):
        raise ValidationError('INVALID_PASSWORD')
```

2021-11-23 06:17 UTC, kyeongraekim requested changes
수정 사항이 하나 더 보이네요!~

2021-11-23 06:17 UTC, kyeongraekim commented on students/jumyoeng/users/views.py
>          except KeyError :
except 문에 Model.DoesNotExist 도 추가해주세요!~ 해당 객체를 모델 클래스에서 잡을 수 없을 때 나는 에러입니다!~

2021-11-23 07:21 UTC, kyeongraekim requested changes
다음 내용 확인후 수정해주세요!

2021-11-23 07:21 UTC, kyeongraekim commented on students/jumyoeng/users/my_lib/validation.py
> +    if not re.search(em_form , email) :
이곳도 match() 메소드를 사용해주셔서 보다 효율적인 코드진행을 가능하게 해주세요~

2021-11-23 07:21 UTC, kyeongraekim commented on students/jumyoeng/users/my_lib/validation.py
> +    pw_form = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'
컨벤션상 변수명은 약어가 아닌 원어 그대로 부탁드립니다~

2021-11-23 07:21 UTC, kyeongraekim commented on students/jumyoeng/users/views.py
>          except KeyError :
해당 except 문 아직 추가수정 반영 전인 것으로 보이네요. Model.DoesNotExist를 꼭 넣어서 없는 객체에 대한 핸들링도 꼭 해주세요~

2021-11-23 15:53 UTC, kyeongraekim approved these changes

2021-11-23 15:53 UTC, merged

2021-11-23 15:53 UTC, kyeongraekim commented
LGTM!~