[장도원] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/27-westagram-backend-2-team pull request #23
Opened 2021-11-23 07:45 UTC by Djangowon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 비밀번호 암호화 적용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입 비밀번호 입력시 암호화되어 db에 저장됨

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-23 10:42 UTC, MinhyukK0 commented on students/dowon/users/views.py
LGTM~

2021-11-23 15:52 UTC, kyeongraekim requested changes
도원님 아래내용 확인하고 수정 반영해주세요!~

2021-11-23 15:52 UTC, kyeongraekim commented on students/dowon/users/views.py
> +                password     = decoded_hashed_password,
가독성을 위해 decoded라는 어휘는 빼주셔도 무방해보입니다!~

2021-11-23 15:52 UTC, kyeongraekim commented on students/dowon/users/views.py
>              return JsonResponse({'massage': 'INVALID_USER'}, status=401)
해당 내용은 6번 과제 진행시 리뷰 달아드리겠습니다!~ 추후 푸시때 기존으로 원상복구 해주신 후 푸시해주세요~

2021-11-23 15:52 UTC, kyeongraekim commented on students/dowon/users/views.py
> +            decoded_hashed_password = hashed_password.decode('utf-8')
두개로 나눠서 선언을 해주지 마시고 hashed_password = abdcefsdwefds... 형식으로 한꺼번에 뭉쳐주시는게 더 깔끔할 것 같네요!~

2021-11-24 08:38 UTC, kyeongraekim approved these changes
LGTM!~

2021-11-24 08:38 UTC, merged