[고민혁] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/27-westagram-backend-2-team pull request #25
Opened 2021-11-23 08:30 UTC by MinhyukK0

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 및 로그인의 bcrypt 적용

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- users.views의 SignupView에 저장되는 비밀번호를 hash된 비밀번호로 저장
- users.views의 SigninView에 로그인확인되는 로직 수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-23 08:56 UTC, haileyjpark commented on students/minhyukko/users/views.py
>          except KeyError:
LGTM~!

2021-11-23 15:48 UTC, kyeongraekim requested changes
민혁님~ LoginView는 추후 6번과제 때 리뷰를 달아드리려고 합니다. 기능별 푸시에 맞게, 깃을 보다 깃답게 사용하는 법에 익숙해지기 위해서 새로 작성한 SignUpView에 해당되는 내용만 푸시를 해주세요!~

2021-11-23 15:48 UTC, kyeongraekim commented on students/minhyukko/users/views.py
> +                password    = hashed_password.decode(),
decode() 문을 hashed_password 변수를 선언할 때 안에 붙이는게 더 가독성에 좋을 것 같네요!~

2021-11-23 15:48 UTC, kyeongraekim commented on students/minhyukko/users/views.py
>              )
32번 라인 성공메세지 영문 오타가 났네요!~

2021-11-24 00:49 UTC, MinhyukK0 commented on students/minhyukko/users/views.py
> +                password    = hashed_password.decode(),
수정했습니다 :D:D

2021-11-24 00:49 UTC, MinhyukK0 commented on students/minhyukko/users/views.py
>              )
수정했습니다 ㅠㅠ

2021-11-24 00:51 UTC, MinhyukK0 commented
리뷰사항 반영 완료했습니다!

2021-11-24 01:06 UTC, kyeongraekim approved these changes
LGTM!~

2021-11-24 01:08 UTC, kyeongraekim requested changes
민혁님 sign up 부분은 문제 없어 보입니다!~ sign in 내용만 기존 코드로 다시 원상 복귀해서 재푸시해주세요. 6번 과제 PR에서 singin 관련 리뷰 달아드리겠습니다!~

2021-11-24 01:22 UTC, MinhyukK0 commented
user.views의 signin 부분 원상복귀 했습니다!

2021-11-24 02:13 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-11-24 02:13 UTC, merged