[유민혁] Mission 1 : Django 초기 세팅
wecode-bootcamp-korea/27-westagram-backend-2-team pull request #3
Opened 2021-11-18 06:04 UTC by MinHyeouk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-18 06:36 UTC, jumyeong33 reviewed
OMG!

2021-11-18 07:53 UTC, lordmyshepherd requested changes

2021-11-18 07:53 UTC, lordmyshepherd commented on students/minhyeouk/requirements.txt
> +
불필요한 라인은 지워주세요~

2021-11-18 07:53 UTC, lordmyshepherd commented on students/minhyeouk/westargram/settings.py
> +
불필요한 import문은 지워주시고, import문 순서를 잘 지켜서 만들어주세요.
위와 같은 순서대로 import 하는 모듈을 정렬해주시고, 파이썬과 장고, 장고와 내가 만든 클래스들 사이에 한 줄씩 띄워주세요.

(python convention 문서 참고해주세요.)

```python
# 파이썬 built-in 모듈
import json
import re

# 외부 모듈
from django.http      import JsonResponse
from django.views     import View

# 내가 만든 사용자 모듈
from users.models     import User
```

2021-11-18 08:49 UTC, kyeongraekim requested changes
아래 간단한 수정 마저 반영해주세요!~

2021-11-18 08:49 UTC, kyeongraekim commented on students/minhyeouk/westargram/settings.py
> +# 파이썬 모듈
불필요한 설명 주석은 지워주셔도 됩니다~

2021-11-18 08:49 UTC, kyeongraekim commented on students/minhyeouk/westargram/settings.py
> +from my_settings    import DATABASES, SECRET_KEY
불필요한 # 설명 주석은 지워주셔도 됩니다~

2021-11-18 08:49 UTC, MinHyeouk commented on students/minhyeouk/westargram/settings.py
> +# 파이썬 모듈
확인했습니다 ~~!

2021-11-18 15:59 UTC, kyeongraekim requested changes
민혁님 딱 한 부분만 수정해주세요!~

2021-11-18 15:59 UTC, kyeongraekim commented on students/minhyeouk/westargram/settings.py
> +# 파이썬 모듈
민혁님!~ #파이썬 모듈, 내가 만든 사용자 모듈, 외부 모듈은 수강생분들의 이해를 돕기위한 가이드용 주석이오니 
실제 개발용 PR이라는 가정하에 위 한글 주석들은 다지워주셔도 됩니다!~ 수정해주시면 바로 머지해드릴게요~

2021-11-19 03:55 UTC, kyeongraekim commented
LGTM!~

2021-11-19 03:55 UTC, merged