[장도원] Mission 2: 모델링
wecode-bootcamp-korea/27-westagram-backend-2-team pull request #8
Opened 2021-11-18 08:19 UTC by rosewoodowon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- User table 생성
* 이름
* 이메일
* 비밀번호
* 연락처(휴대폰)
* 정보

2021-11-18 08:20 UTC, jumyeong33 commented
conflict !

2021-11-18 09:04 UTC, kyeongraekim requested changes
도원님 아래 내용 확인해서 수정해주세요!~

2021-11-18 09:04 UTC, kyeongraekim commented on students/dowon/users/models.py
> +from django.db import models
위코드 컨벤션에 맞게 전체적인 문서 수정이 필요해보입니다~

https://www.notion.so/wecode/wecode-Python-Coding-Convention-0a293f18b2244dfeb1005273d0a9dc75

위 링크에서 필요한 부분 확인하셔서 전체 코드 내용에 잘 접목시켜주세요!~

2021-11-18 09:04 UTC, kyeongraekim commented on students/dowon/users/models.py
> +    password = models.CharField(max_length=45)
비밀번호는 나중에 암호화가 되어서 저장될 기획을 감안하여 max_length를  넉넉히 주세요!~

2021-11-18 09:04 UTC, kyeongraekim commented on students/dowon/users/models.py
> +    phone = models.IntegerField(unique=True)
전화번호 변수명은 명확하게 주시는게 좋습니다. phone_number로 바꿔주시고 다양한 특수기호(예시 - & + in  국제번호)가 들어갈 가능성을 감안하여 다른 Field 로 속성값을 변경해주세요!~

2021-11-18 09:05 UTC, lordmyshepherd requested changes

2021-11-18 09:05 UTC, lordmyshepherd commented on students/dowon/users/models.py
> +# Create your models here.
주석은 지워주세요!

2021-11-18 09:05 UTC, lordmyshepherd commented on students/dowon/users/models.py
> +from enum import unique
필요한 import문인지 고민하고 수정해주세요!

2021-11-18 09:05 UTC, lordmyshepherd commented on students/dowon/users/models.py
> +
데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2021-11-18 09:05 UTC, lordmyshepherd commented on students/dowon/users/models.py
> +    password = models.CharField(max_length=45)
password는 이후에 암호화해서 저장해야하기 때문에 max_length=200으로 수정해주세요~

2021-11-18 09:50 UTC, kyeongraekim requested changes
간단한 수정사항이 더 있습니다~ 반영해주세요!~

2021-11-18 09:50 UTC, kyeongraekim commented on students/dowon/users/models.py
> +
컨벤션 맞게 다시 정렬 해주세요!~
[링크 바로가기](https://www.notion.so/wecode/wecode-Python-Coding-Convention-0a293f18b2244dfeb1005273d0a9dc75) 에 Code Align에 해당되는 부분을 잘 살펴주세요~

2021-11-18 09:50 UTC, kyeongraekim commented on students/dowon/users/models.py
> +# Create your models here.
아직 주석을 덜 지워주셨네요!~

2021-11-18 10:11 UTC, kyeongraekim requested changes
컨벤션 관련 정렬 다시 한 번 부탁드릴게요!~

2021-11-18 10:11 UTC, kyeongraekim commented on students/dowon/users/models.py
> +# Create your models here.
공백 정렬이 다소 이상하게 변하였어요~ Vim과 VSC 를 혼용해서 사용하시다가 중간에 의도치않은 tab 공백들이 들어간 것으로 보이네요!~ 깃허브 상에서 보았을 때 문제 없게끔 수정 부탁드릴게요!~

2021-11-18 15:52 UTC, kyeongraekim commented
도원님~ 모델링 관련 PR인데 모델파일을 지우신 것 같아 보여요~ 혹시 의도하신 바가 맞는지 확인 부탁드릴게요!~

2021-11-19 08:55 UTC, kyeongraekim approved these changes
LGTM!~

2021-11-19 08:55 UTC, merged